/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.items;

import com.operation.FileOperate;
import javax.swing.JOptionPane;

/**
 *
 * @author ltz
 */
public class JeanItem extends javax.swing.JFrame {

    /**
     * Creates new form Jean
     */
    public JeanItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        color = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        cancellBtn = new javax.swing.JButton();
        nameInput = new javax.swing.JTextField();
        xsInput = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        sInput = new javax.swing.JTextField();
        xs = new javax.swing.JLabel();
        mInput = new javax.swing.JTextField();
        s = new javax.swing.JLabel();
        lInput = new javax.swing.JTextField();
        m = new javax.swing.JLabel();
        xlInput = new javax.swing.JTextField();
        l = new javax.swing.JLabel();
        colorInput = new javax.swing.JTextField();
        xl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Jean");

        color.setText("Color");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancellBtn.setText("Cancell");
        cancellBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancellBtnActionPerformed(evt);
            }
        });

        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });

        xsInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xsInputActionPerformed(evt);
            }
        });

        name.setText("Name");

        xs.setText("XS");

        mInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mInputActionPerformed(evt);
            }
        });

        s.setText("S");

        m.setText("M");

        l.setText("L");

        xl.setText("XL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(cancellBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(color)
                            .addComponent(xl)
                            .addComponent(l)
                            .addComponent(m)
                            .addComponent(s)
                            .addComponent(xs)
                            .addComponent(name))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mInput)
                            .addComponent(lInput)
                            .addComponent(xlInput)
                            .addComponent(colorInput)
                            .addComponent(xsInput)
                            .addComponent(sInput)
                            .addComponent(nameInput))))
                .addGap(202, 202, 202))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name)
                        .addGap(18, 18, 18)
                        .addComponent(xs)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s)
                            .addComponent(sInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l)
                    .addComponent(lInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xl)
                    .addComponent(xlInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(color)
                    .addComponent(colorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancellBtn))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        FileOperate filedemo=new FileOperate();
                                String xs=xsInput.getText().trim();
				String s=sInput.getText().trim();
				String m=mInput.getText().trim();
				String l=lInput.getText().trim();
				String xl=xlInput.getText().trim();
				String color=colorInput.getText().trim();
				
				int num;
				String str="";
				
				try {
				    
					str="XS";
				    num=Integer.valueOf(xs);
				    
				    str="S";
				    num=Integer.valueOf(s);
				    
				    str="M";
				    num=Integer.valueOf(m);
				    
				    str="L";
				    num=Integer.valueOf(l);
				    
				    str="XL";
				    num=Integer.valueOf(xl);
				    
				   
				    
				   } catch (Exception e1) {
					   JOptionPane.showMessageDialog(null, str+" must be a Number","ERROR", JOptionPane.ERROR_MESSAGE);
					   return;
				   }
				
				String all=name+"%"+xs+"%"+s+"%"+m+"%"+l+"%"+xl+"%"+color;
				
				
				
				filedemo.WriteFile(all, "jacket.txt");
				
				JOptionPane.showMessageDialog(null, "Saved Successfully !","Congratulations", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancellBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancellBtnActionPerformed

        // TODO add your handling code here:
        JeanItem.this.setVisible(false);
        JeanItem.this.dispose();

    }//GEN-LAST:event_cancellBtnActionPerformed

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputActionPerformed

    private void xsInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xsInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xsInputActionPerformed

    private void mInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JeanItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JeanItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JeanItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JeanItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JeanItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancellBtn;
    private javax.swing.JLabel color;
    private javax.swing.JTextField colorInput;
    private javax.swing.JLabel l;
    private javax.swing.JTextField lInput;
    private javax.swing.JLabel m;
    private javax.swing.JTextField mInput;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel s;
    private javax.swing.JTextField sInput;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel xl;
    private javax.swing.JTextField xlInput;
    private javax.swing.JLabel xs;
    private javax.swing.JTextField xsInput;
    // End of variables declaration//GEN-END:variables
}
