/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;
import com.items.*;

import com.items.JacketItem;
import com.operation.FileOperate;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author ltz
 */
public class Main extends javax.swing.JFrame implements ActionListener,WindowListener, ChangeListener {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        
        jtp.addChangeListener(this);
		
	this.getContentPane().add(jtp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jtp = new javax.swing.JTabbedPane();
        addpane = new javax.swing.JPanel();
        tipLabel = new javax.swing.JLabel();
        ItemList = new javax.swing.JComboBox<>();
        nextBtn = new javax.swing.JButton();
        salepane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        XSInput = new javax.swing.JTextField();
        SInput = new javax.swing.JTextField();
        MInput = new javax.swing.JTextField();
        LInput = new javax.swing.JTextField();
        XLInput = new javax.swing.JTextField();
        colorInput = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        addcombox = new javax.swing.JComboBox<>();
        vippane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vipTable = new javax.swing.JTable();
        supplierpane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplierTable = new javax.swing.JTable();
        productpane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        bestsellerpane = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        bestsellerTable = new javax.swing.JTable();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Store");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(200, 150));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("false"), this, org.jdesktop.beansbinding.BeanProperty.create("resizable"));
        bindingGroup.addBinding(binding);

        tipLabel.setText("Please select the Item you want to Add");

        ItemList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jean", "Jacket", "T-shirt", "Vip", "Supplier", "BestSeller" }));

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addpaneLayout = new javax.swing.GroupLayout(addpane);
        addpane.setLayout(addpaneLayout);
        addpaneLayout.setHorizontalGroup(
            addpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addpaneLayout.createSequentialGroup()
                .addGroup(addpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addpaneLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(ItemList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(nextBtn))
                    .addGroup(addpaneLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(tipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        addpaneLayout.setVerticalGroup(
            addpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addpaneLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(tipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(addpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextBtn))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jtp.addTab("Add", addpane);

        jLabel2.setText("name of Sale");

        jLabel1.setText("name of Type");

        jLabel7.setText("number of XS");

        jLabel8.setText("number of S");

        jLabel9.setText("number of M");

        jLabel10.setText("number of L");

        jLabel11.setText("number of XL");

        jLabel12.setText("color of Sale");

        XLInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XLInputActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        addcombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jean", "Jacket", "T-shirt", "Product" }));

        javax.swing.GroupLayout salepaneLayout = new javax.swing.GroupLayout(salepane);
        salepane.setLayout(salepaneLayout);
        salepaneLayout.setHorizontalGroup(
            salepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salepaneLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(salepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(saveBtn))
                .addGap(63, 63, 63)
                .addGroup(salepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(resetBtn)
                        .addComponent(nameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addComponent(XSInput)
                        .addComponent(SInput)
                        .addComponent(MInput)
                        .addComponent(LInput)
                        .addComponent(XLInput)
                        .addComponent(colorInput))
                    .addComponent(addcombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        salepaneLayout.setVerticalGroup(
            salepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salepaneLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(salepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(addcombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(salepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(salepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(XSInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(salepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(SInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(salepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(MInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(salepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(LInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(salepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(XLInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(salepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(colorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(salepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(resetBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtp.addTab("Sale", salepane);

        vipTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Phone Number", "Email", "Money Spent", "Favorite Brand"
            }
        ));
        jScrollPane2.setViewportView(vipTable);

        javax.swing.GroupLayout vippaneLayout = new javax.swing.GroupLayout(vippane);
        vippane.setLayout(vippaneLayout);
        vippaneLayout.setHorizontalGroup(
            vippaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vippaneLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        vippaneLayout.setVerticalGroup(
            vippaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vippaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jtp.addTab("Vips", vippane);

        supplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Phone Number", "Email"
            }
        ));
        jScrollPane1.setViewportView(supplierTable);

        javax.swing.GroupLayout supplierpaneLayout = new javax.swing.GroupLayout(supplierpane);
        supplierpane.setLayout(supplierpaneLayout);
        supplierpaneLayout.setHorizontalGroup(
            supplierpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierpaneLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        supplierpaneLayout.setVerticalGroup(
            supplierpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierpaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jtp.addTab("Supplier", supplierpane);

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Number of XS", "Number of S", "Number of M", "Number of L", "Number of XL", "Color"
            }
        ));
        jScrollPane3.setViewportView(productTable);

        javax.swing.GroupLayout productpaneLayout = new javax.swing.GroupLayout(productpane);
        productpane.setLayout(productpaneLayout);
        productpaneLayout.setHorizontalGroup(
            productpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productpaneLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        productpaneLayout.setVerticalGroup(
            productpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productpaneLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))
        );

        jtp.addTab("Product", productpane);

        bestsellerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Profits", "Brand"
            }
        ));
        jScrollPane4.setViewportView(bestsellerTable);

        javax.swing.GroupLayout bestsellerpaneLayout = new javax.swing.GroupLayout(bestsellerpane);
        bestsellerpane.setLayout(bestsellerpaneLayout);
        bestsellerpaneLayout.setHorizontalGroup(
            bestsellerpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bestsellerpaneLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        bestsellerpaneLayout.setVerticalGroup(
            bestsellerpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bestsellerpaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jtp.addTab("BestSeller", bestsellerpane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtp, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
                                String item=(String)ItemList.getSelectedItem();
				
				
				
				 if(item.equals("Jacket"))
				{
					jacket = new JacketItem();
					jacket.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

					jacket.setVisible(true);
					System.out.println(item);
				}
                                 
                                 else if(item.equals("Jean"))
				{
					
					jean = new JeanItem();
					jean.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

					jean.setVisible(true);
					
					
					//System.out.println(item);
				}
                                 
                                 else if(item.equals("T-shirt"))
				{
					tshirt = new TshirtItem();
					tshirt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
					tshirt.setVisible(true);
					//System.out.println(item);
				}
                                 
                                else if(item.equals("Vip"))
				{
					vip = new VipItem();
					vip.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
					vip.setVisible(true);
					//System.out.println(item);
				}
				
				else if(item.equals("Supplier"))
				{
					supplier = new SupplierItem();
					supplier.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
					supplier.setVisible(true);
					//System.out.println(item);
				}
                                 
                                else if(item.equals("BestSeller"))
				{
					bestseller = new BestSellerItem();
					bestseller.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
					bestseller.setVisible(true);
					//System.out.println(item);
				}
				
				
        
    }//GEN-LAST:event_nextBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
                                FileOperate filedemo=new FileOperate();
                                
                                String name=nameInput.getText().trim();
				
				String xs=XSInput.getText().trim();
				String s=SInput.getText().trim();
				String m=MInput.getText().trim();
				String l=LInput.getText().trim();
				String xl=XLInput.getText().trim();
				String color=colorInput.getText().trim();
				
				int num;
				String str="";
				
				try {
				    
					str="XS";
				    num=Integer.valueOf(xs);
				    
				    str="S";
				    num=Integer.valueOf(s);
				    
				    str="M";
				    num=Integer.valueOf(m);
				    
				    str="L";
				    num=Integer.valueOf(l);
				    
				    str="XL";
				    num=Integer.valueOf(xl);
				    
				   
				    
				   } catch (Exception e1) {
					   JOptionPane.showMessageDialog(null, str+" must be a Number","ERROR", JOptionPane.ERROR_MESSAGE);
					   return;
				   }
				
				
				
				
				String item=(String)addcombox.getSelectedItem();
				
				
				
				String content=name+"%"+xs+"%"+s+"%"+m+"%"+l+"%"+xl+"%"+color;
				
				boolean success=Sale(content,item,filedemo);
				
				if(success)
				{
					JOptionPane.showMessageDialog(null, "Operation succeeded !","Congratulations", JOptionPane.INFORMATION_MESSAGE);
				}
				
				else
				{
					JOptionPane.showMessageDialog(null, "Can not found this record !","Failed", JOptionPane.OK_OPTION);
					return;
				}
				
				//save sale records to the file
				String all=item+"%"+name+"%"+xs+"%"+s+"%"+m+"%"+l+"%"+xl+"%"+color;
				
				filedemo.WriteFile(all, "sale.txt");
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void XLInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XLInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XLInputActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
                                nameInput.setText("");
				XSInput.setText("");
				SInput.setText("");
				MInput.setText("");
				LInput.setText("");
				XLInput.setText("");
				colorInput.setText("");
    }//GEN-LAST:event_resetBtnActionPerformed

   
        
    @Override
	public void stateChanged(ChangeEvent e) {
		// TODO Auto-generated method stub
		
		
		 String name = jtp.getSelectedComponent().toString();
                 
                FileOperate filedemo=new FileOperate();
		 
		 if(name.equals(vippane.toString()))
		 {
                   ArrayList<String> strList=new ArrayList<String>();
		
		strList=filedemo.ReadObject("vip.txt");
		
		//System.out.println(strList);
		
		String[][] itemList = {
				
		};
		
		int len=strList.size();
		
		if(len>0)
		{
			itemList=new String[len][5];
			
			for(int i=0;i<strList.size();i++)
			{
				
				
				String []str=strList.get(i).split("%");
				
				
				
				itemList[i]=str;
				
				
				
			}
		}
                String[] tags = {"Name","Phone Number","Email","Money Spent","Favorite Brand"};
                vipTable.setModel(new javax.swing.table.DefaultTableModel(itemList,tags ));
		
		 }
		 
		 if(name.equals(productpane.toString()))
		 {
			
		
		ArrayList<String> jeanList=new ArrayList<String>();
		ArrayList<String> jacketList=new ArrayList<String>();
		ArrayList<String> tshirtList=new ArrayList<String>();
		
		jeanList=filedemo.ReadObject("jean.txt");
		jacketList=filedemo.ReadObject("jacket.txt");
		tshirtList=filedemo.ReadObject("tshirt.txt");
		
		//System.out.println(strList);
		
		String[][] itemList = {
				
		};
		
		int len=jeanList.size()+jacketList.size()+tshirtList.size();
		
		if(len>0)
		{
			itemList=new String[len][7];
			
			int row=0;
			
			for(int i=0;i<jeanList.size();i++)
			{
				
				
				String []str=jeanList.get(i).split("%");
				
				
				
				itemList[i]=str;
				
				
				
			}
			
			row=jeanList.size();
			
			for(int j=0;j<jacketList.size();j++)
			{
				
				
				String []str=jacketList.get(j).split("%");
				
				
				
				itemList[row+j]=str;
				
				
				
			}
			
			row=row+jacketList.size();
			
			for(int k=0;k<tshirtList.size();k++)
			{
				
				
				String []str=tshirtList.get(k).split("%");
				
				
				
				itemList[row+k]=str;
				
				
				
			}
			
		}
                String[] tags = {"Name","Number Of XS","Number Of S","Number Of M","Number Of L","Number Of XL","Color"};
                
               productTable.setModel(new javax.swing.table.DefaultTableModel(itemList,tags ));
                     
		 }
		 
		 if(name.equals(bestsellerpane.toString()))
		 {
			 //bestsellerpane.updateTable();
                     ArrayList<String> strList=new ArrayList<String>();
		
		strList=filedemo.ReadObject("bestseller.txt");
		
		//System.out.println(strList);
		
		String[][] itemList = {
				
		};
		
		int len=strList.size();
		
		if(len>0)
		{
			
			itemList=new String[len][3];
			
			for(int i=0;i<strList.size();i++)
			{
				
				
				String []str=strList.get(i).split("%");
				
				
				
				itemList[i]=str;
				
				
				
			}
			
			sortItemList(itemList);
		}
		
                     
                     String[] tags = {"Name","Profits","Brand"};
                     bestsellerTable.setModel(new javax.swing.table.DefaultTableModel(itemList,tags ));
		 }
		 
		 if(name.equals(supplierpane.toString()))
		 {
			 //supplierpane.updateTable();
                     
                     ArrayList<String> strList=new ArrayList<String>();
		
		strList=filedemo.ReadObject("supplier.txt");
		
		//System.out.println(strList);
		
		String[][] itemList = {
				
		};
		
		int len=strList.size();
		
		if(len>0)
		{
			
			itemList=new String[len][3];
			
			for(int i=0;i<strList.size();i++)
			{
				
				
				String []str=strList.get(i).split("%");
				
				
				
				itemList[i]=str;
				
				
				
			}
		}
                     
                     
                     String[] tags = {"Name","Phone","Email"};
                     supplierTable.setModel(new javax.swing.table.DefaultTableModel(itemList,tags ));
                     
		 }
		 
		
		 
		 
		 
	}
        
        public void sortItemList(String [][]itemlist){
		
		int len=itemlist.length;
		String []temp;
		
		for(int i=0;i<len-1;i++)
		{
			for(int j=i+1;j<len;j++)
			{
				if(Integer.valueOf(itemlist[i][1])<Integer.valueOf(itemlist[j][1]))
				{
					temp=itemlist[i];
					itemlist[i]=itemlist[j];
					itemlist[j]=temp;
				}
			}
		}
		
	}
	public boolean Sale(String content,String type,FileOperate filedemo)
	{
		
		
		boolean success=false;
		
		
		
		if(type.contains("Jean"))
		{
			success=filedemo.SaleObject(content,"jean.txt");
		}
		
		else if(type.equals("Jacket"))
		{
			success=filedemo.SaleObject(content,"jacket.txt");
		}
		
		else if(type.equals("T-shirt"))
		{
			success=filedemo.SaleObject(content,"tshirt.txt");
		}
		
		else
		{
			success=filedemo.SaleObject(content,"product.txt");
		}
			
			
		return success;
	}
        
        
	public void actionPerformed(ActionEvent e)
	{
	}
	
	

	@Override
	public void windowOpened(WindowEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void windowClosing(WindowEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void windowClosed(WindowEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void windowIconified(WindowEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void windowDeiconified(WindowEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void windowActivated(WindowEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void windowDeactivated(WindowEvent e) {
		// TODO Auto-generated method stub
		
	}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ItemList;
    private javax.swing.JTextField LInput;
    private javax.swing.JTextField MInput;
    private javax.swing.JTextField SInput;
    private javax.swing.JTextField XLInput;
    private javax.swing.JTextField XSInput;
    private javax.swing.JComboBox<String> addcombox;
    private javax.swing.JPanel addpane;
    private javax.swing.JTable bestsellerTable;
    private javax.swing.JPanel bestsellerpane;
    private javax.swing.JTextField colorInput;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jtp;
    private javax.swing.JTextField nameInput;
    private javax.swing.JButton nextBtn;
    private javax.swing.JTable productTable;
    private javax.swing.JPanel productpane;
    private javax.swing.JButton resetBtn;
    private javax.swing.JPanel salepane;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTable supplierTable;
    private javax.swing.JPanel supplierpane;
    private javax.swing.JLabel tipLabel;
    private javax.swing.JTable vipTable;
    private javax.swing.JPanel vippane;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
     private JacketItem jacket;
     private JeanItem jean;
     private TshirtItem tshirt;
     private VipItem vip;
     private SupplierItem supplier;
     private BestSellerItem bestseller;
}
